package net.javierjimenez.SeriesTV;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

public class SeriesController {
	@FXML
	private TextField search;
	@FXML
	private ComboBox temporadas;
	@FXML
	private ListView list_cap;
	@FXML
	private Label cap_cast;
	@FXML
	private Label cap_lat;
	@FXML
	private Label cap_eng;
	@FXML
	private Label cap_vos;

	// Event Listener on Button.onAction
	@FXML
	public void busquedaSeries(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#temporadas].onAction
	@FXML
	public void listaTemporadas(ActionEvent event) {
		// TODO Autogenerated
	}
}
